## Project: PDF creator to payroll

In [4]:
import pandas as pd
import numpy as np
import pdfkit
import os
from generate_html import * 

# Config of wkhtmltopdf
path_to_wkhtmltopdf = r'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe'
config = pdfkit.configuration(wkhtmltopdf=path_to_wkhtmltopdf)

# dataframe
data = pd.read_csv('data_company_IT.csv')  
data

,ID,First Name,Last Name,Start Date,Contract Type,Role,Area,Bank,Bank_Account_ID,Account_Type,...,Unemployment Insurance,union dues,Deductions,Income tax%,Assets,Income tax,Legal Discounts,Net Salary,Month,Year
0,11111,Brett,Bell,2022-05-25,Fixed-Term Contract,Manager,Marketing,Santander,80699531,Deposito Account,...,44,22,806,7.09,5330,350.955,1156.955,4173.045,May,2025
1,11113,John,Bowen,2023-11-20,Fixed-Term Contract,Manager,System,Santander,36906460,Deposito Account,...,44,22,806,7.09,5030,329.685,1135.685,3894.315,May,2025
2,11115,Bruce,Brown,2024-01-10,Permanent Contract,Manager,Analytics,Scotiabank,90323311,Current Account,...,44,22,806,7.09,5030,329.685,1135.685,3894.315,May,2025
3,11117,Melanie,Gentry,2022-05-30,Permanent Contract,Manager,HR,Ban Chile,81835200,Deposito Account,...,44,22,806,7.09,5330,350.955,1156.955,4173.045,May,2025
4,11119,Elizabeth,Paul,2024-08-28,Permanent Contract,Manager,IT,Scotiabank,56316314,Deposito Account,...,44,22,806,7.09,4730,308.415,1114.415,3615.585,May,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,11171,Robin,Ruiz,2023-03-11,Permanent Contract,Business Analyst Senior,Analytics,ITAU,24308363,Deposito Account,...,26,13,490,4.52,3630,146.900,636.900,2993.100,May,2025
66,11177,Victoria,Cooper,2024-09-29,Fixed-Term Contract,Business Analyst Senior,Analytics,Santander,60436823,Deposito Account,...,26,13,490,4.52,3030,119.780,609.780,2420.220,May,2025
67,11178,Regina,Roman,2023-12-26,Fixed-Term Contract,Business Analyst Senior,Analytics,BCI,92654773,Current Account,...,26,13,490,4.52,3330,133.340,623.340,2706.660,May,2025
68,11179,Angela,Anderson,2023-01-28,Permanent Contract,Business Analyst Senior,Analytics,ITAU,15624004,Current Account,...,26,13,490,4.52,3630,146.900,636.900,2993.100,May,2025
69,11167,Susan,Robinson,2024-01-17,Fixed-Term Contract,Business Analyst,Analytics,Santander,98992405,Current Account,...,20,10,361,2.20,2630,49.500,410.500,2219.500,May,2025

In [ ]:
df = data.iloc[0:1] # example , replace for real dataframe


# create a folder 
output_folder = "Employees_pdf"
os.makedirs(output_folder, exist_ok=True)

logo_path = os.path.abspath("fake_company.png")
footer1_path = os.path.abspath("fake_signature.png")
footer2_path = os.path.abspath("worker_signature.png")
logo_url = f"file:///{logo_path.replace(os.sep, '/')}"
footer1_url = f"file:///{footer1_path.replace(os.sep, '/')}"
footer2_url = f"file:///{footer2_path.replace(os.sep, '/')}"

options = {
    'enable-local-file-access': None
}

for index, row in df.iterrows():
    html_content = generate_html_v2(row, logo_url, footer1_url,footer2_url) #change HTML version
    output_pdf_path = os.path.join(output_folder, f"{row['First Name']}_{row['Last Name']}_payment.pdf")
    pdfkit.from_string(html_content, output_pdf_path, configuration=config, options=options)
    print(f"{row['First Name']}_{row['Last Name']}_payment.pdf")

Bruce_Brown_payment.pdf